#define INTEGER 1
#define FLOAT 2
#define BOOLEAN 3
#define ARITHMETIC_OPERATOR 4
#define LOGICAL_OPERATOR 5
#define ASSIGNMENT_OPERATOR 6
#define RELATIONAL_OPERATOR 7
#define SHORTHAND_OPERATOR 8
#define CONDITIONAL_OPERATOR 9
#define COMPARATOR 10
#define FUNCTION 11
#define LOOP_STATEMENT 12
#define CONDITIONAL_STATEMENT 13
#define DELIMETER 14
#define IDENTIFIER 15
#define KEYWORD 16
#define STRING 17

